project:
  type: website

website:
  title: "Emergecy response coordination"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: requests.qmd
        text: Requests
      - href: results.qmd
        text: Results
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

